# 실습 1) 전처리 연습
### Tokenize / Cleansing & Normalization / Stemming & Lemmatization

1. 데이터셋(corpus)을 찾는다. (만들어진 데이터셋, 크롤링, ...)
    - **🐿️ 이어지는 실습에 쓸 수 있을 법한 데이터 찾기 Tip**
    - 여러 문장으로 이루어진 데이터셋이라면 일단 good
        - 리뷰 등 이어지지 않는 짧은 문장 여러 건 ok
        - 소설 등 이어지는 긴 문장 여러 건 ok
    - 대화형 데이터셋도 good
        - QnA로 구성되어 있는 corpus도 좋고
        - 일반적인 대화로 구성되어 있는 corpus도 좋아요~
    - 특정 도메인에 대한 정보를 담고 있는 데이터셋도 good
2. 전처리를 해본다.
    - 텍스트 자체를 깔끔하게 만드는 것까지만

**사용 데이터셋**: Yelp Open Dataset 리뷰 샘플 (영어, 긍/부정 라벨 포함)  
- 여러 짧은 문장(리뷰)이 여러 건 포함된 데이터  
- 이어지는 실습 2, 3번에서도 동일 데이터 사용

### 1. 데이터셋 준비

Yelp Open Dataset은 용량이 매우 크므로, 수업에서 배운 형태(긍정/부정 라벨 + 리뷰 텍스트)와 동일한 구조로 샘플 데이터를 발췌, 구성

In [1]:
import pandas as pd

# Yelp 리뷰 데이터 생성
# label: 1 = 긍정, 0 = 부정
yelp_review_txt = {
    'review': [
        "The food was absolutely amazing! Best burger I've ever had.",
        "Terrible service. We waited for over an hour and the food was cold.",
        "Loved the cozy atmosphere and the friendly staff. Will definitely come back!",
        "The pizza was undercooked and the place was dirty. Very disappointing.",
        "Great sushi! Fresh ingredients and reasonable prices.",
        "Worst dining experience ever. Rude staff and overpriced food.",
        "Absolutely delicious pasta. The chef really knows his craft.",
        "Not worth the money. Bland food and tiny portions.",
        "Outstanding steaks and excellent wine selection. Highly recommend!",
        "Waited 30 minutes to be seated and the food tasted like cardboard.",
        "The desserts are heavenly! Chocolate cake was to die for.",
        "Mediocre at best. Nothing special about the food or the service.",
        "Fresh and flavorful dishes. The staff was incredibly attentive.",
        "Overpriced and underwhelming. Would not recommend to anyone.",
        "Perfect brunch spot! Eggs benedict were perfectly cooked.",
        "Horrible experience. Found a hair in my soup and nobody apologized.",
        "Wonderful place with a great view. Food was top notch.",
        "Service was slow and the food was barely lukewarm when it arrived.",
        "Five stars all around! Authentic flavors and generous portions.",
        "Disappointing meal. Expected much better based on the reviews."
    ],
    'label': [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0]
}

df = pd.DataFrame(yelp_review_txt)  # 딕셔너리 -> DataFrame으로 변환
print(f'데이터 크기: {df.shape}')
df

데이터 크기: (20, 2)

                                               review  label
0   The food was absolutely amazing! Best burger I...      1
1   Terrible service. We waited for over an hour a...      0
2   Loved the cozy atmosphere and the friendly sta...      1
3   The pizza was undercooked and the place was di...      0
4   Great sushi! Fresh ingredients and reasonable ...      1
5   Worst dining experience ever. Rude staff and o...      0
6   Absolutely delicious pasta. The chef really kn...      1
7   Not worth the money. Bland food and tiny porti...      0
8   Outstanding steaks and excellent wine selectio...      1
9   Waited 30 minutes to be seated and the food ta...      0
10  The desserts are heavenly! Chocolate cake was ...      1
11  Mediocre at best. Nothing special about the fo...      0
12  Fresh and flavorful dishes. The staff was incr...      1
13  Overpriced and underwhelming. Would not recomm...      0
14  Perfect brunch spot! Eggs benedict were perfec...      1
15  Horrible experience. Found a hair in my soup a...      0
16  Wonderful place with a great view. Food was to...      1
17  Service was slow and the food was barely lukew...      0
18  Five stars all around! Authentic flavors and g...      1
19  Disappointing meal. Expected much better based...      0

In [2]:
# 실습 2, 3에서 활용하기 위해 CSV로 저장
df.to_csv('yelp_sample.csv', index=False)
print('yelp_sample.csv saved')

yelp_sample.csv saved

### 2. 토큰화 (Tokenization)

In [3]:
import nltk
# nltk 리소스 다운로드
nltk.download('punkt')      # 토큰화에 필요한 데이터
nltk.download('punkt_tab')  # punkt의 추가 테이블
nltk.download('stopwords')  # 불용어 리스트

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Playdata\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\Playdata\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Playdata\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [4]:
print(type(yelp_review_txt))
print(yelp_review_txt)

<class 'dict'>
{'review': ["The food was absolutely amazing! Best burger I've ever had.", 'Terrible service. We waited for over an hour and the food was cold.', 'Loved the cozy atmosphere and the friendly staff. Will definitely come back!', 'The pizza was undercooked and the place was dirty. Very disappointing.', 'Great sushi! Fresh ingredients and reasonable prices.', 'Worst dining experience ever. Rude staff and overpriced food.', 'Absolutely delicious pasta. The chef really knows his craft.', 'Not worth the money. Bland food and tiny portions.', 'Outstanding steaks and excellent wine selection. Highly recommend!', 'Waited 30 minutes to be seated and the food tasted like cardboard.', 'The desserts are heavenly! Chocolate cake was to die for.', 'Mediocre at best. Nothing special about the food or the service.', 'Fresh and flavorful dishes. The staff was incredibly attentive.', 'Overpriced and underwhelming. Would not recommend to anyone.', 'Perfect brunch spot! Eggs benedict were perfectly cooked.', 'Horrible experience. Found a hair in my soup and nobody apologized.', 'Wonderful place with a great view. Food was top notch.', 'Service was slow and the food was barely lukewarm when it arrived.', 'Five stars all around! Authentic flavors and generous portions.', 'Disappointing meal. Expected much better based on the reviews.'], 'label': [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0]}

In [55]:
sample_review_txt = df['review'][0]
print(sample_review_txt)

The food was absolutely amazing! Best burger I've ever had.

단위별 tokenize

In [6]:
from nltk.tokenize import word_tokenize

# 문장 토큰화
nltk.sent_tokenize(yelp_review_txt)

['The food was absolutely amazing!', "Best burger I've ever had."]

In [7]:
# 단어 토큰화
nltk.word_tokenize(yelp_review_txt)

['The',
 'food',
 'was',
 'absolutely',
 'amazing',
 '!',
 'Best',
 'burger',
 'I',
 "'ve",
 'ever',
 'had',
 '.']

In [8]:
# 문장별 단어 토큰화 
for sent in nltk.sent_tokenize(yelp_review_txt):
    print(nltk.word_tokenize(sent))

['The', 'food', 'was', 'absolutely', 'amazing', '!']
['Best', 'burger', 'I', "'ve", 'ever', 'had', '.']

In [10]:
# Subword Tokenize

# !pip install transformers

In [9]:
from transformers import BertTokenizer

tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

sample_review = df['review'][0]
print(sample_review)
print(tokenizer.tokenize(sample_review))

The food was absolutely amazing! Best burger I've ever had.
['the', 'food', 'was', 'absolutely', 'amazing', '!', 'best', 'burger', 'i', "'", 've', 'ever', 'had', '.']

In [10]:
# 비교
print('word_tokenize:', word_tokenize(sample_review))
print('BERT tokenize:', tokenizer.tokenize(sample_review))

word_tokenize: ['The', 'food', 'was', 'absolutely', 'amazing', '!', 'Best', 'burger', 'I', "'ve", 'ever', 'had', '.']
BERT tokenize: ['the', 'food', 'was', 'absolutely', 'amazing', '!', 'best', 'burger', 'i', "'", 've', 'ever', 'had', '.']

In [12]:
from nltk.tokenize import word_tokenize

print('word_tokenize:', word_tokenize('overpriced'))

print('BERT tokenize:', tokenizer.tokenize('overpriced'))

word_tokenize: ['overpriced']
BERT tokenize: ['over', '##pr', '##ice', '##d']

In [13]:
# 문자 단위 토큰화
list(sample_review)

['T',
 'h',
 'e',
 ' ',
 'f',
 'o',
 'o',
 'd',
 ' ',
 'w',
 'a',
 's',
 ' ',
 'a',
 'b',
 's',
 'o',
 'l',
 'u',
 't',
 'e',
 'l',
 'y',
 ' ',
 'a',
 'm',
 'a',
 'z',
 'i',
 'n',
 'g',
 '!',
 ' ',
 'B',
 'e',
 's',
 't',
 ' ',
 'b',
 'u',
 'r',
 'g',
 'e',
 'r',
 ' ',
 'I',
 "'",
 'v',
 'e',
 ' ',
 'e',
 'v',
 'e',
 'r',
 ' ',
 'h',
 'a',
 'd',
 '.']

In [14]:
from nltk.tokenize import WordPunctTokenizer, word_tokenize

sample_review = "The food was absolutely amazing! Best burger I've ever had."
        
# 단어/구두점으로 토큰 구분
word_punct_tknz = WordPunctTokenizer()
print(word_punct_tknz.tokenize(yelp_review_txt))  
print(word_tokenize(yelp_review_txt))

['The', 'food', 'was', 'absolutely', 'amazing', '!', 'Best', 'burger', 'I', "'", 've', 'ever', 'had', '.']
['The', 'food', 'was', 'absolutely', 'amazing', '!', 'Best', 'burger', 'I', "'ve", 'ever', 'had', '.']

In [15]:
from nltk.tokenize import TreebankWordTokenizer

# 구두점을 고려한 토큰화

text = """
The food was absolutely amazing! Best burger I've ever had. 
Terrible service. We waited for over an hour and the food was cold.
Loved the cozy atmosphere and the friendly staff. Will definitely come back!
"""
treebank_word_tknz = TreebankWordTokenizer()
print(treebank_word_tknz.tokenize(text))

# word_tokenize(): TreebankWordTokenizer + PunktSentenceTokenizer
print(word_tokenize(text))

['The', 'food', 'was', 'absolutely', 'amazing', '!', 'Best', 'burger', 'I', "'ve", 'ever', 'had.', 'Terrible', 'service.', 'We', 'waited', 'for', 'over', 'an', 'hour', 'and', 'the', 'food', 'was', 'cold.', 'Loved', 'the', 'cozy', 'atmosphere', 'and', 'the', 'friendly', 'staff.', 'Will', 'definitely', 'come', 'back', '!']
['The', 'food', 'was', 'absolutely', 'amazing', '!', 'Best', 'burger', 'I', "'ve", 'ever', 'had', '.', 'Terrible', 'service', '.', 'We', 'waited', 'for', 'over', 'an', 'hour', 'and', 'the', 'food', 'was', 'cold', '.', 'Loved', 'the', 'cozy', 'atmosphere', 'and', 'the', 'friendly', 'staff', '.', 'Will', 'definitely', 'come', 'back', '!']

품사 태깅 ```nltk pos_tag()```

In [18]:
# nltk.download('averaged_perceptron_tagger')         # 영어 품사 태깅 모델
# nltk.download('averaged_perceptron_tagger_eng')     # 영어 품사 태깅 모델 (영어 전용 분리)

In [16]:
from nltk.tag import pos_tag

tokens = word_tokenize(yelp_review_txt)
pos_tag(tokens)

[('The', 'DT'),
 ('food', 'NN'),
 ('was', 'VBD'),
 ('absolutely', 'RB'),
 ('amazing', 'JJ'),
 ('!', '.'),
 ('Best', 'JJS'),
 ('burger', 'NN'),
 ('I', 'PRP'),
 ("'ve", 'VBP'),
 ('ever', 'RB'),
 ('had', 'VBN'),
 ('.', '.')]

spacy 이용

In [21]:
import spacy

spacy_nlp = spacy.load('en_core_web_sm')

In [22]:
sample_review = df['review'][0]
tokens = spacy_nlp(sample_review)

for token in tokens:
    print(token.text, ":", token.pos_)

The : DET
food : NOUN
was : AUX
absolutely : ADV
amazing : ADJ
! : PUNCT
Best : ADJ
burger : NOUN
I : PRON
've : AUX
ever : ADV
had : VERB
. : PUNCT

In [23]:
# 토큰화에 따른 감정분석 비교
nltk.download('vader_lexicon')

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     C:\Users\Playdata\AppData\Roaming\nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

True

In [27]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer


analyzer = SentimentIntensityAnalyzer()
analyzer.polarity_scores((sample_review))

{'neg': 0.0, 'neu': 0.474, 'pos': 0.526, 'compound': 0.8709}

In [30]:
texts = [
        "The food was absolutely amazing! Best burger I've ever had.",
        "Terrible service. We waited for over an hour and the food was cold.",
        "Loved the cozy atmosphere and the friendly staff. Will definitely come back!",
        "The pizza was undercooked and the place was dirty. Very disappointing.",
        "Great sushi! Fresh ingredients and reasonable prices.",
        "Worst dining experience ever. Rude staff and overpriced food.",
        "Absolutely delicious pasta. The chef really knows his craft.",
        "Not worth the money. Bland food and tiny portions.",
        "Outstanding steaks and excellent wine selection. Highly recommend!",
        "Waited 30 minutes to be seated and the food tasted like cardboard.",
        "The desserts are heavenly! Chocolate cake was to die for.",
        "Mediocre at best. Nothing special about the food or the service.",
        "Fresh and flavorful dishes. The staff was incredibly attentive.",
        "Overpriced and underwhelming. Would not recommend to anyone.",
        "Perfect brunch spot! Eggs benedict were perfectly cooked.",
        "Horrible experience. Found a hair in my soup and nobody apologized.",
        "Wonderful place with a great view. Food was top notch.",
        "Service was slow and the food was barely lukewarm when it arrived.",
        "Five stars all around! Authentic flavors and generous portions.",
        "Disappointing meal. Expected much better based on the reviews."
    ]

for text in texts:
    print(text, analyzer.polarity_scores(text))

The food was absolutely amazing! Best burger I've ever had. {'neg': 0.0, 'neu': 0.474, 'pos': 0.526, 'compound': 0.8709}
Terrible service. We waited for over an hour and the food was cold. {'neg': 0.205, 'neu': 0.795, 'pos': 0.0, 'compound': -0.4767}
Loved the cozy atmosphere and the friendly staff. Will definitely come back! {'neg': 0.0, 'neu': 0.471, 'pos': 0.529, 'compound': 0.8777}
The pizza was undercooked and the place was dirty. Very disappointing. {'neg': 0.415, 'neu': 0.585, 'pos': 0.0, 'compound': -0.7501}
Great sushi! Fresh ingredients and reasonable prices. {'neg': 0.0, 'neu': 0.428, 'pos': 0.572, 'compound': 0.7712}
Worst dining experience ever. Rude staff and overpriced food. {'neg': 0.504, 'neu': 0.496, 'pos': 0.0, 'compound': -0.7964}
Absolutely delicious pasta. The chef really knows his craft. {'neg': 0.0, 'neu': 0.667, 'pos': 0.333, 'compound': 0.6115}
Not worth the money. Bland food and tiny portions. {'neg': 0.172, 'neu': 0.828, 'pos': 0.0, 'compound': -0.1695}
Outstanding steaks and excellent wine selection. Highly recommend! {'neg': 0.0, 'neu': 0.317, 'pos': 0.683, 'compound': 0.8953}
Waited 30 minutes to be seated and the food tasted like cardboard. {'neg': 0.0, 'neu': 0.815, 'pos': 0.185, 'compound': 0.3612}
The desserts are heavenly! Chocolate cake was to die for. {'neg': 0.241, 'neu': 0.494, 'pos': 0.265, 'compound': 0.1007}
Mediocre at best. Nothing special about the food or the service. {'neg': 0.146, 'neu': 0.582, 'pos': 0.272, 'compound': 0.4482}
Fresh and flavorful dishes. The staff was incredibly attentive. {'neg': 0.0, 'neu': 0.777, 'pos': 0.223, 'compound': 0.3182}
Overpriced and underwhelming. Would not recommend to anyone. {'neg': 0.232, 'neu': 0.768, 'pos': 0.0, 'compound': -0.2755}
Perfect brunch spot! Eggs benedict were perfectly cooked. {'neg': 0.0, 'neu': 0.423, 'pos': 0.577, 'compound': 0.8478}
Horrible experience. Found a hair in my soup and nobody apologized. {'neg': 0.254, 'neu': 0.58, 'pos': 0.167, 'compound': -0.296}
Wonderful place with a great view. Food was top notch. {'neg': 0.0, 'neu': 0.385, 'pos': 0.615, 'compound': 0.8625}
Service was slow and the food was barely lukewarm when it arrived. {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Five stars all around! Authentic flavors and generous portions. {'neg': 0.0, 'neu': 0.69, 'pos': 0.31, 'compound': 0.5562}
Disappointing meal. Expected much better based on the reviews. {'neg': 0.244, 'neu': 0.534, 'pos': 0.221, 'compound': -0.0772}

토큰화에 따라 감정 분석 결과가 달라짐

In [33]:
corpus = df['review'][10]

# 1. WordPunctTokenizer로 토큰화
tokenizer = WordPunctTokenizer()
tokens1 = tokenizer.tokenize(corpus)
print(tokens1)
text1 = " ".join(tokens1)  #각각 다시 문자열로 합치고 vader 감성분석기로 돌림

# 2. word_tokenize로 토큰화
tokens2 = word_tokenize(corpus)
print(tokens2)
text2 = " ".join(tokens2)

print(analyzer.polarity_scores(text1))
print(analyzer.polarity_scores(text2))


# neg: 0.241   # 부정 비율
# neu: 0.494   # 중립 비율
# pos: 0.265   # 긍정 비율
# compound: 0.1007  # 전체 감성 점수 (-1 ~ 1)
# heavenly라는 긍정단어가 있는데도 불구하고 compound가 0.1로 낮음. 
# "to die for"은 긍정적 관용표현인데, VADER가 die를 부정단어로 인식해서 점수가 낮아진 것 같음.

['The', 'desserts', 'are', 'heavenly', '!', 'Chocolate', 'cake', 'was', 'to', 'die', 'for', '.']
['The', 'desserts', 'are', 'heavenly', '!', 'Chocolate', 'cake', 'was', 'to', 'die', 'for', '.']
{'neg': 0.241, 'neu': 0.494, 'pos': 0.265, 'compound': 0.1007}
{'neg': 0.241, 'neu': 0.494, 'pos': 0.265, 'compound': 0.1007}

### 3. 정제 & 정규화 (Cleansing & Normalization)

**정제**: 노이즈 제거 (특수문자, 이모지, 구두점 등)  
**정규화**: 표현 통일 (대소문자 통합, 불용어 제거 등)

In [52]:
import re
from nltk.corpus import stopwords

raw_text = ' '.join(df['review'])

#불필요한 기호 제거
clean_text = re.sub(r'[^\w\s]', '', raw_text)
print('기호 제거:', clean_text)

# 소문자 변환
clean_text = clean_text.lower()
print('소문자 변환:', clean_text)

# 공백 정리
clean_text = ' '.join(clean_text.split())
print('공백 정리:', clean_text)

# 숫자 제거
clean_text = re.sub(r'\d+', '', clean_text)
print('숫자 제거:', clean_text)

# 불용어 제거
en_stopwords = stopwords.words('english')
print('불용어 예시:', en_stopwords[:20])
print('불용어 총 개수:', len(en_stopwords))

tokens = clean_text.split()
tokens = [token for token in tokens if token not in en_stopwords]
print('불용어 제거:', tokens)

# 짧은 단어 제거 (길이 2 이하)-> 불용어 제거하는거랑 결과 동일하니까 주석처리.
# tokens = [token for token in tokens if len(token) > 2]
# print('짧은 단어 제거:', tokens)

기호 제거: The food was absolutely amazing Best burger Ive ever had Terrible service We waited for over an hour and the food was cold Loved the cozy atmosphere and the friendly staff Will definitely come back The pizza was undercooked and the place was dirty Very disappointing Great sushi Fresh ingredients and reasonable prices Worst dining experience ever Rude staff and overpriced food Absolutely delicious pasta The chef really knows his craft Not worth the money Bland food and tiny portions Outstanding steaks and excellent wine selection Highly recommend Waited 30 minutes to be seated and the food tasted like cardboard The desserts are heavenly Chocolate cake was to die for Mediocre at best Nothing special about the food or the service Fresh and flavorful dishes The staff was incredibly attentive Overpriced and underwhelming Would not recommend to anyone Perfect brunch spot Eggs benedict were perfectly cooked Horrible experience Found a hair in my soup and nobody apologized Wonderful place with a great view Food was top notch Service was slow and the food was barely lukewarm when it arrived Five stars all around Authentic flavors and generous portions Disappointing meal Expected much better based on the reviews
소문자 변환: the food was absolutely amazing best burger ive ever had terrible service we waited for over an hour and the food was cold loved the cozy atmosphere and the friendly staff will definitely come back the pizza was undercooked and the place was dirty very disappointing great sushi fresh ingredients and reasonable prices worst dining experience ever rude staff and overpriced food absolutely delicious pasta the chef really knows his craft not worth the money bland food and tiny portions outstanding steaks and excellent wine selection highly recommend waited 30 minutes to be seated and the food tasted like cardboard the desserts are heavenly chocolate cake was to die for mediocre at best nothing special about the food or the service fresh and flavorful dishes the staff was incredibly attentive overpriced and underwhelming would not recommend to anyone perfect brunch spot eggs benedict were perfectly cooked horrible experience found a hair in my soup and nobody apologized wonderful place with a great view food was top notch service was slow and the food was barely lukewarm when it arrived five stars all around authentic flavors and generous portions disappointing meal expected much better based on the reviews
공백 정리: the food was absolutely amazing best burger ive ever had terrible service we waited for over an hour and the food was cold loved the cozy atmosphere and the friendly staff will definitely come back the pizza was undercooked and the place was dirty very disappointing great sushi fresh ingredients and reasonable prices worst dining experience ever rude staff and overpriced food absolutely delicious pasta the chef really knows his craft not worth the money bland food and tiny portions outstanding steaks and excellent wine selection highly recommend waited 30 minutes to be seated and the food tasted like cardboard the desserts are heavenly chocolate cake was to die for mediocre at best nothing special about the food or the service fresh and flavorful dishes the staff was incredibly attentive overpriced and underwhelming would not recommend to anyone perfect brunch spot eggs benedict were perfectly cooked horrible experience found a hair in my soup and nobody apologized wonderful place with a great view food was top notch service was slow and the food was barely lukewarm when it arrived five stars all around authentic flavors and generous portions disappointing meal expected much better based on the reviews
숫자 제거: the food was absolutely amazing best burger ive ever had terrible service we waited for over an hour and the food was cold loved the cozy atmosphere and the friendly staff will definitely come back the pizza was undercooked and the place was dirty very disappointing great sushi fresh ingredients and reasonable prices worst dining experience ever rude staff and overpriced food absolutely delicious pasta the chef really knows his craft not worth the money bland food and tiny portions outstanding steaks and excellent wine selection highly recommend waited  minutes to be seated and the food tasted like cardboard the desserts are heavenly chocolate cake was to die for mediocre at best nothing special about the food or the service fresh and flavorful dishes the staff was incredibly attentive overpriced and underwhelming would not recommend to anyone perfect brunch spot eggs benedict were perfectly cooked horrible experience found a hair in my soup and nobody apologized wonderful place with a great view food was top notch service was slow and the food was barely lukewarm when it arrived five stars all around authentic flavors and generous portions disappointing meal expected much better based on the reviews
불용어 예시: ['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an', 'and', 'any', 'are', 'aren', "aren't", 'as', 'at', 'be', 'because', 'been']
불용어 총 개수: 198
불용어 제거: ['food', 'absolutely', 'amazing', 'best', 'burger', 'ive', 'ever', 'terrible', 'service', 'waited', 'hour', 'food', 'cold', 'loved', 'cozy', 'atmosphere', 'friendly', 'staff', 'definitely', 'come', 'back', 'pizza', 'undercooked', 'place', 'dirty', 'disappointing', 'great', 'sushi', 'fresh', 'ingredients', 'reasonable', 'prices', 'worst', 'dining', 'experience', 'ever', 'rude', 'staff', 'overpriced', 'food', 'absolutely', 'delicious', 'pasta', 'chef', 'really', 'knows', 'craft', 'worth', 'money', 'bland', 'food', 'tiny', 'portions', 'outstanding', 'steaks', 'excellent', 'wine', 'selection', 'highly', 'recommend', 'waited', 'minutes', 'seated', 'food', 'tasted', 'like', 'cardboard', 'desserts', 'heavenly', 'chocolate', 'cake', 'die', 'mediocre', 'best', 'nothing', 'special', 'food', 'service', 'fresh', 'flavorful', 'dishes', 'staff', 'incredibly', 'attentive', 'overpriced', 'underwhelming', 'would', 'recommend', 'anyone', 'perfect', 'brunch', 'spot', 'eggs', 'benedict', 'perfectly', 'cooked', 'horrible', 'experience', 'found', 'hair', 'soup', 'nobody', 'apologized', 'wonderful', 'place', 'great', 'view', 'food', 'top', 'notch', 'service', 'slow', 'food', 'barely', 'lukewarm', 'arrived', 'five', 'stars', 'around', 'authentic', 'flavors', 'generous', 'portions', 'disappointing', 'meal', 'expected', 'much', 'better', 'based', 'reviews']

### 4. 어간 추출 & 표제어 추출 (Stemming & Lemmatization)

In [53]:
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer

stemmer = PorterStemmer()
lemmatizer = WordNetLemmatizer()

stemmed = [stemmer.stem(token) for token in tokens]
lemmatized = [lemmatizer.lemmatize(token, pos='v') for token in tokens] # - 동사 기준

print(tokens)
print(stemmed)
print(lemmatized)

['food', 'absolutely', 'amazing', 'best', 'burger', 'ive', 'ever', 'terrible', 'service', 'waited', 'hour', 'food', 'cold', 'loved', 'cozy', 'atmosphere', 'friendly', 'staff', 'definitely', 'come', 'back', 'pizza', 'undercooked', 'place', 'dirty', 'disappointing', 'great', 'sushi', 'fresh', 'ingredients', 'reasonable', 'prices', 'worst', 'dining', 'experience', 'ever', 'rude', 'staff', 'overpriced', 'food', 'absolutely', 'delicious', 'pasta', 'chef', 'really', 'knows', 'craft', 'worth', 'money', 'bland', 'food', 'tiny', 'portions', 'outstanding', 'steaks', 'excellent', 'wine', 'selection', 'highly', 'recommend', 'waited', 'minutes', 'seated', 'food', 'tasted', 'like', 'cardboard', 'desserts', 'heavenly', 'chocolate', 'cake', 'die', 'mediocre', 'best', 'nothing', 'special', 'food', 'service', 'fresh', 'flavorful', 'dishes', 'staff', 'incredibly', 'attentive', 'overpriced', 'underwhelming', 'would', 'recommend', 'anyone', 'perfect', 'brunch', 'spot', 'eggs', 'benedict', 'perfectly', 'cooked', 'horrible', 'experience', 'found', 'hair', 'soup', 'nobody', 'apologized', 'wonderful', 'place', 'great', 'view', 'food', 'top', 'notch', 'service', 'slow', 'food', 'barely', 'lukewarm', 'arrived', 'five', 'stars', 'around', 'authentic', 'flavors', 'generous', 'portions', 'disappointing', 'meal', 'expected', 'much', 'better', 'based', 'reviews']
['food', 'absolut', 'amaz', 'best', 'burger', 'ive', 'ever', 'terribl', 'servic', 'wait', 'hour', 'food', 'cold', 'love', 'cozi', 'atmospher', 'friendli', 'staff', 'definit', 'come', 'back', 'pizza', 'undercook', 'place', 'dirti', 'disappoint', 'great', 'sushi', 'fresh', 'ingredi', 'reason', 'price', 'worst', 'dine', 'experi', 'ever', 'rude', 'staff', 'overpr', 'food', 'absolut', 'delici', 'pasta', 'chef', 'realli', 'know', 'craft', 'worth', 'money', 'bland', 'food', 'tini', 'portion', 'outstand', 'steak', 'excel', 'wine', 'select', 'highli', 'recommend', 'wait', 'minut', 'seat', 'food', 'tast', 'like', 'cardboard', 'dessert', 'heavenli', 'chocol', 'cake', 'die', 'mediocr', 'best', 'noth', 'special', 'food', 'servic', 'fresh', 'flavor', 'dish', 'staff', 'incred', 'attent', 'overpr', 'underwhelm', 'would', 'recommend', 'anyon', 'perfect', 'brunch', 'spot', 'egg', 'benedict', 'perfectli', 'cook', 'horribl', 'experi', 'found', 'hair', 'soup', 'nobodi', 'apolog', 'wonder', 'place', 'great', 'view', 'food', 'top', 'notch', 'servic', 'slow', 'food', 'bare', 'lukewarm', 'arriv', 'five', 'star', 'around', 'authent', 'flavor', 'gener', 'portion', 'disappoint', 'meal', 'expect', 'much', 'better', 'base', 'review']
['food', 'absolutely', 'amaze', 'best', 'burger', 'ive', 'ever', 'terrible', 'service', 'wait', 'hour', 'food', 'cold', 'love', 'cozy', 'atmosphere', 'friendly', 'staff', 'definitely', 'come', 'back', 'pizza', 'undercooked', 'place', 'dirty', 'disappoint', 'great', 'sushi', 'fresh', 'ingredients', 'reasonable', 'price', 'worst', 'din', 'experience', 'ever', 'rude', 'staff', 'overprice', 'food', 'absolutely', 'delicious', 'pasta', 'chef', 'really', 'know', 'craft', 'worth', 'money', 'bland', 'food', 'tiny', 'portion', 'outstanding', 'steaks', 'excellent', 'wine', 'selection', 'highly', 'recommend', 'wait', 'minutes', 'seat', 'food', 'taste', 'like', 'cardboard', 'desserts', 'heavenly', 'chocolate', 'cake', 'die', 'mediocre', 'best', 'nothing', 'special', 'food', 'service', 'fresh', 'flavorful', 'dish', 'staff', 'incredibly', 'attentive', 'overprice', 'underwhelming', 'would', 'recommend', 'anyone', 'perfect', 'brunch', 'spot', 'egg', 'benedict', 'perfectly', 'cook', 'horrible', 'experience', 'find', 'hair', 'soup', 'nobody', 'apologize', 'wonderful', 'place', 'great', 'view', 'food', 'top', 'notch', 'service', 'slow', 'food', 'barely', 'lukewarm', 'arrive', 'five', 'star', 'around', 'authentic', 'flavor', 'generous', 'portion', 'disappoint', 'meal', 'expect', 'much', 'better', 'base', 'review']

### 5. 전체 데이터 전처리

In [57]:
# 실습 2, 3에서 전처리된 데이터 사용해야 하므로 리뷰 한 건씩 개별적으로 전처리해서 DataFrame으로 저장

def preprocess(text):
    text = re.sub(r'[^\w\s]', '', text)    # 기호 제거
    text = text.lower()                    # 소문자 변환
    text = ' '.join(text.split())          # 공백 정리
    text = re.sub(r'\d+', '', text)        # 숫자 제거
    tokens = text.split()
    tokens = [t for t in tokens if t not in en_stopwords]        # 불용어 제거
    tokens = [lemmatizer.lemmatize(t, pos='v') for t in tokens]  # 정규화
    return ' '.join(tokens)

df['cleaned_review'] = df['review'].apply(preprocess)
df.to_csv('yelp_preprocessed.csv', index=False)
print('yelp_preprocessed.csv saved')
df

yelp_preprocessed.csv saved

,review,label,cleaned_review,tokens
0,The food was absolutely amazing! Best burger I...,1,food absolutely amaze best burger ive ever,food absolutely amaze best burger ive ever
1,Terrible service. We waited for over an hour a...,0,terrible service wait hour food cold,terrible service wait hour food cold
2,Loved the cozy atmosphere and the friendly sta...,1,love cozy atmosphere friendly staff definitely...,love cozy atmosphere friendly staff definitely...
3,The pizza was undercooked and the place was di...,0,pizza undercooked place dirty disappoint,pizza undercooked place dirty disappoint
4,Great sushi! Fresh ingredients and reasonable ...,1,great sushi fresh ingredients reasonable price,great sushi fresh ingredients reasonable price
5,Worst dining experience ever. Rude staff and o...,0,worst din experience ever rude staff overprice...,worst din experience ever rude staff overprice...
6,Absolutely delicious pasta. The chef really kn...,1,absolutely delicious pasta chef really know craft,absolutely delicious pasta chef really know craft
7,Not worth the money. Bland food and tiny porti...,0,worth money bland food tiny portion,worth money bland food tiny portion
8,Outstanding steaks and excellent wine selectio...,1,outstanding steaks excellent wine selection hi...,outstanding steaks excellent wine selection hi...
9,Waited 30 minutes to be seated and the food ta...,0,wait minutes seat food taste like cardboard,wait minutes seat food taste like cardboard
10,The desserts are heavenly! Chocolate cake was ...,1,desserts heavenly chocolate cake die,desserts heavenly chocolate cake die
11,Mediocre at best. Nothing special about the fo...,0,mediocre best nothing special food service,mediocre best nothing special food service
12,Fresh and flavorful dishes. The staff was incr...,1,fresh flavorful dish staff incredibly attentive,fresh flavorful dish staff incredibly attentive
13,Overpriced and underwhelming. Would not recomm...,0,overprice underwhelming would recommend anyone,overprice underwhelming would recommend anyone
14,Perfect brunch spot! Eggs benedict were perfec...,1,perfect brunch spot egg benedict perfectly cook,perfect brunch spot egg benedict perfectly cook
15,Horrible experience. Found a hair in my soup a...,0,horrible experience find hair soup nobody apol...,horrible experience find hair soup nobody apol...
16,Wonderful place with a great view. Food was to...,1,wonderful place great view food top notch,wonderful place great view food top notch
17,Service was slow and the food was barely lukew...,0,service slow food barely lukewarm arrive,service slow food barely lukewarm arrive
18,Five stars all around! Authentic flavors and g...,1,five star around authentic flavor generous por...,five star around authentic flavor generous por...
19,Disappointing meal. Expected much better based...,0,disappoint meal expect much better base review,disappoint meal expect much better base review